/*
 * data_model_snapshot.c
 * 
 * Snapshot of code generation data model.
 * This information is included in the executable file
 * and does not affect any memory content in the embedded device.
 */
 
__attribute__((section("diagnostics_cinfo, info"), keep)) char MCAF_data_model_snapshot[] =
  "{\"motor\": {\"Tfr\": 0.0048125,\"B\": 1.2211e-05,\"Lq\": 2.96544849632e-06,\"po"
  "leCount\": 6,\"rated_current\": 11.0,\"J\": 6e-06,\"velocity\": {\"nominal\": 20"
  "94.39510239,\"maximum\": 2303.83461263,\"units\": \"rad\\/s\"},\"L\": 2.51e-06,"
  "\"R\": 0.0809,\"current\": {\"maximum\": {\"continuous\": 11.0,\"peak\": 16.0},"
  "\"units\": \"A\"},\"Ld\": 2.05455150368e-06,\"Ke\": 0.00562941090491,\"id\": \"D"
  "ucted Fan\"},\"controller\": {\"encoder\": {\"tracking_loop\": {\"zeta\": 1.5}},"
  "\"foc\": {\"feedback\": {\"voltage_delay\": 0}},\"pll\": {\"delay_match\": true,"
  "\"properties\": {\"reference\": false},\"keInverseScaling\": 1.0},\"operation\":"
  " {\"min_deceleration_time\": null},\"dyn_current\": {\"maxgain\": 1.1},\"zsmt\":"
  " {\"errorLimit\": 0.99997,\"properties\": {\"independent\": true,\"reference\": "
  "false},\"duration\": {\"lockDelay\": 0.05},\"probe\": {\"accumGain\": 1.0}},\"fa"
  "ult_detect\": {\"recovery\": {\"attempts\": 3}}},\"metadata\": {\"MCC\": {\"arch"
  "itecture\": \"melody\",\"peripherals\": {\"instances\": [{\"name\": \"ADC1\",\"t"
  "ype\": \"adc\"},{\"name\": \"PWM\",\"type\": \"pwm_hs\"},{\"name\": \"SCCP1\",\""
  "type\": \"timer\"},{\"name\": \"TMR1\",\"type\": \"timer\"},{\"name\": \"UART2\""
  ",\"type\": \"uart\"},{\"name\": \"OPA1\",\"type\": \"opa\"},{\"name\": \"OPA2\","
  "\"type\": \"opa\"},{\"name\": \"OPA3\",\"type\": \"opa\"},{\"name\": \"CMP1\",\""
  "type\": \"cmp\"},{\"name\": \"UART3\",\"type\": \"uart\"}]},\"version\": \"5.8.4"
  "\",\"peripheral_library\": {\"name\": \"melody\",\"version\": \"NA\"}},\"data_mo"
  "del\": {\"schema_version\": 5},\"motorBench\": {\"commit_id\": \"c114bdc6e8ebb44"
  "adc1b5cd1e6b92ea0b107647e\",\"version\": \"2.55.0\"},\"MCAF\": {\"build\": {\"co"
  "mmit_id\": \"132024\",\"date_str\": \"2026 Feb 13\",\"hostname\": \"motor-contro"
  "l-mcaf-tags-builder-r9-2frc31-1-4qzv8-0zfbw-3kggr\",\"time\": 1771007857.63,\"ti"
  "me_iso\": \"2026-02-13T18:37:37.630250\",\"time_str\": \"2026 Feb 13 18:37\",\"t"
  "ype\": \"release\",\"username\": \"jenkins\",\"version\": \"R9\\/RC31\"},\"build"
  "_time\": 1771007857.63,\"build_time_iso\": \"2026-02-13T18:37:37.630250\",\"buil"
  "d_time_str\": \"2026 Feb 13 18:37\",\"commit_id\": \"132024\",\"version\": \"R9"
  "\\/RC31\"}},\"scdata\": {\"setup\": {\"communications\": {\"baudrate\": 625000},"
  "\"analysis\": {\"spindown_time\": {\"units\": \"s\",\"value\": 1.0},\"max_motor_"
  "speed\": {\"units\": \"rad\\/s mechanical\",\"value\": 2094.4}},\"calibration\":"
  " {\"vdc\": {\"units\": \"V\",\"value\": 12.0},\"resistor\": {\"units\": \"ohms\""
  ",\"value\": 12.0}}}},\"autotune_result\": {\"current\": {\"Kp\": 0.0609473480089"
  ",\"phase_margin\": 80.0,\"wc\": 12108.11483,\"Ki\": 737.957488274,\"pi_phase_lag"
  "\": 45.0},\"velocity\": {\"Kp\": 0.0761593629186,\"phase_margin\": 65.0,\"wc\": "
  "108.828008985,\"Ki\": 1.46144594743,\"pi_phase_lag\": 10.0}},\"code_generation_t"
  "ag_map\": {\"application\": \"sample\",\"diagnostics\": \"x2cscope\"},\"operatin"
  "g_range\": {\"velocity\": {\"units_qualifier\": \"mechanical\",\"units\": \"rad"
  "\\/s\",\"minimum\": 174.533}},\"build\": {\"hardware_spec\": \"mclv2:33ck256mp50"
  "8_extopamp_pim\",\"normfactor_associations\": [{\"context\": null,\"annotations"
  "\": [{\"typerefs\": [\"MCAF_U_CURRENT_ABC\",\"MCAF_U_CURRENT_ALPHABETA\",\"MCAF_"
  "U_CURRENT_DQ\",\"MCAF_U_CURRENT\",\"MCAF_MOTOR_DATA.omegaCtrl.outMin\",\"MCAF_MO"
  "TOR_DATA.omegaCtrl.outMax\"],\"unit\": \"I\",\"q\": 15},{\"typerefs\": [\"MCAF_M"
  "OTOR_DATA.omegaCtrl.integrator\"],\"unit\": \"I\",\"q\": 15},{\"typerefs\": [\"M"
  "CAF_U_VOLTAGE_ABC\",\"MCAF_U_VOLTAGE_ALPHABETA\",\"MCAF_U_VOLTAGE_DQ\",\"MCAF_U_"
  "VOLTAGE\",\"MCAF_MOTOR_DATA.idCtrl.outMin\",\"MCAF_MOTOR_DATA.idCtrl.outMax\",\""
  "MCAF_MOTOR_DATA.iqCtrl.outMin\",\"MCAF_MOTOR_DATA.iqCtrl.outMax\"],\"unit\": \"V"
  "\",\"q\": 15},{\"typerefs\": [\"MCAF_MOTOR_DATA.idCtrl.integrator\",\"MCAF_MOTOR"
  "_DATA.iqCtrl.integrator\"],\"unit\": \"V\",\"q\": 31},{\"typerefs\": [\"MCAF_U_D"
  "UTYCYCLE_ABC\"],\"unit\": 1,\"q\": 15},{\"typerefs\": [\"MCAF_U_ANGLE_ELEC\"],\""
  "unit\": \"theta_e\",\"q\": 15},{\"typerefs\": [\"MCAF_U_ANGLE_MECH\"],\"unit\": "
  "\"theta_m\",\"q\": 15},{\"typerefs\": [\"MCAF_U_VELOCITY_MECH\"],\"unit\": \"ome"
  "ga_m\",\"q\": 15},{\"typerefs\": [\"MCAF_U_VELOCITY_ELEC\"],\"unit\": \"omega_e"
  "\",\"q\": 15},{\"typerefs\": [\"MCAF_U_VELOCITY_DTHETA_ELEC_DT\"],\"unit\": \"dt"
  "heta_elec_dt\",\"q\": 15},{\"typerefs\": [\"MCAF_U_TEMPERATURE\"],\"unit\": \"Te"
  "mperature\",\"q\": 15},{\"typerefs\": [\"MCAF_U_DIMENSIONLESS\",\"MCAF_U_DIMENSI"
  "ONLESS_SINCOS\"],\"unit\": 1,\"q\": 15},{\"typerefs\": [\"MCAF_U_NORMALIZED_GAIN"
  "\"],\"unit\": 1,\"q\": 14},{\"typerefs\": [\"MCAF_U_NORMALIZED_Q15\"],\"unit\": "
  "1,\"q\": 15}]}]},\"drive\": {\"iout\": {\"measurement\": {\"compensation\": {\"c"
  "hannels\": [\"a\",\"b\"],\"values\": {\"a\": [1.0,0.0],\"b\": [0.0,1.0]},\"offse"
  "t\": {\"samples\": 128,\"filterGain\": 0.25},\"gain\": {\"samples\": 128}}},\"ti"
  "me_constant\": 1.8814e-07,\"fullscale\": 22.0,\"maximum\": {\"continuous\": 10.0"
  ",\"peak\": 10.0},\"units\": \"A\"},\"estimator\": {\"type\": \"pll\",\"runtimeSe"
  "lect\": false,\"smo\": {\"ke_low_limit\": 0.01},\"omega1\": 732.0,\"tau\": 0.002"
  "19},\"flux_control\": {\"emag_tau\": 0.001638,\"idref_tau\": 0.006552},\"tempera"
  "ture\": {\"fullscale\": 327.68,\"units\": \"C\"},\"pwm\": {\"adc_sampling_delay"
  "\": 0,\"period\": 5e-05,\"duty_cycle\": {\"maximum\": 0.975,\"minimum\": 0.009},"
  "\"deadtime\": 1e-06},\"mcaf\": {\"adc\": {\"triggerSettings\": {\"noTrigger\": "
  "\"NO_TRIGGER\",\"trigger1\": \"PWM1_TRIGGER1\",\"trigger2\": \"PWM1_TRIGGER2\"},"
  "\"channels\": {\"prefix\": \"MCAF_ADC_\",\"critical\": [\"PHASEA_CURRENT\",\"PHA"
  "SEB_CURRENT\",\"PHASEC_CURRENT\",\"DCLINK_CURRENT\",\"DCLINK_VOLTAGE\"],\"requir"
  "ed\": {\"single_channel\": [\"DCLINK_CURRENT\",\"DCLINK_VOLTAGE\"],\"dual_channe"
  "l\": [\"PHASEA_CURRENT\",\"PHASEB_CURRENT\",\"DCLINK_VOLTAGE\"],\"triple_channel"
  "\": [\"PHASEA_CURRENT\",\"PHASEB_CURRENT\",\"PHASEC_CURRENT\",\"DCLINK_VOLTAGE\""
  "]},\"optional\": [\"POTENTIOMETER\",\"PHASEA_VOLTAGE\",\"PHASEB_VOLTAGE\",\"PHAS"
  "EC_VOLTAGE\",\"BRIDGE_TEMPERATURE\",\"ABSREF_VOLTAGE\"],\"fullList\": [{\"name\""
  ": \"PHASEA_CURRENT\",\"c_fragment\": \"PhaseACurrent\",\"description\": \"phase "
  "A current\",\"type\": \"current\"},{\"name\": \"PHASEB_CURRENT\",\"c_fragment\":"
  " \"PhaseBCurrent\",\"description\": \"phase B current\",\"type\": \"current\"},{"
  "\"name\": \"PHASEC_CURRENT\",\"c_fragment\": \"PhaseCCurrent\",\"description\": "
  "\"phase C current\",\"type\": \"current\"},{\"name\": \"PHASEA_VOLTAGE\",\"c_fra"
  "gment\": \"PhaseAVoltage\",\"description\": \"phase A voltage\",\"type\": \"volt"
  "age\"},{\"name\": \"PHASEB_VOLTAGE\",\"c_fragment\": \"PhaseBVoltage\",\"descrip"
  "tion\": \"phase B voltage\",\"type\": \"voltage\"},{\"name\": \"PHASEC_VOLTAGE\""
  ",\"c_fragment\": \"PhaseCVoltage\",\"description\": \"phase C voltage\",\"type\""
  ": \"voltage\"},{\"name\": \"DCLINK_CURRENT\",\"c_fragment\": \"DCLinkCurrent\","
  "\"description\": \"DC link current\",\"type\": \"current\"},{\"name\": \"DCLINK_"
  "VOLTAGE\",\"c_fragment\": \"DCLinkVoltage\",\"description\": \"DC link voltage\""
  ",\"type\": \"voltage\"},{\"name\": \"POTENTIOMETER\",\"c_fragment\": \"Potentiom"
  "eter\",\"description\": \"potentiometer voltage\",\"type\": \"voltage\"},{\"name"
  "\": \"BRIDGE_TEMPERATURE\",\"c_fragment\": \"BridgeTemperature\",\"description\""
  ": \"bridge temperature voltage\",\"type\": \"voltage\"},{\"name\": \"ABSREF_VOLT"
  "AGE\",\"c_fragment\": \"AbsoluteReferenceVoltage\",\"description\": \"absolute r"
  "eference voltage\",\"type\": \"voltage\"}]}}},\"metadata\": {\"name\": \"dsPIC33"
  "CDVC256MP506 Drone Ref Design\",\"id\": \"cdvc-drone02\"},\"vdc\": {\"time_const"
  "ant\": 6.11e-06,\"nominal\": 12.0,\"fullscale\": 36.3,\"maximum\": 16.0,\"units"
  "\": \"V\",\"minimum\": 10.0},\"configuration\": {\"identification\": {\"id\": \""
  "cdvc-drone02\",\"displayName\": \"dsPIC33CDVC256MP506 Drone Ref Design\",\"descr"
  "iption\": \"Pallas Reference Design\"},\"characteristics\": {\"device\": \"dsPIC"
  "33CDVC256MP506\",\"gateDriver\": {\"device\": \"MCP8021\",\"configuration\": {\""
  "sleepMode\": \"standby\",\"shortCircuitDetect\": false,\"underVoltageLockout\": "
  "false},\"pins\": {\"RX\": \"RC12\",\"TX\": \"RC12\",\"fault\": \"RB12\",\"output"
  "Enable\": \"RB13\"}},\"voltage\": {\"phase\": {\"timeConstant\": 6.11e-06,\"full"
  "scale\": 36.3},\"dcLink\": {\"timeConstant\": 6.11e-06,\"fullscale\": 36.3,\"min"
  "imum\": 10.0,\"maximum\": 16.0,\"default\": 12.0}},\"current\": {\"phase\": {\"f"
  "ullscale\": 22.0,\"maximum\": {\"continuous\": 10},\"timeConstant\": 1.8814e-07}"
  ",\"dcLink\": {\"fullscale\": 22.0,\"timeConstant\": 1.8814e-07}},\"pwm\": {\"fre"
  "quency\": {\"minimum\": 1000,\"maximum\": 100000,\"default\": 20000},\"deadTime"
  "\": {\"minimum\": 6.7e-07,\"maximum\": 6e-06,\"default\": 1e-06},\"dutyCycle\": "
  "{\"minimum\": 0.009,\"maximum\": 0.975}}},\"peripherals\": {\"oscillator\": {\"c"
  "lockSource\": \"internal FRC\",\"inputClockFrequency\": 8000000},\"adc\": {\"cur"
  "rent\": {\"a\": {\"channel\": \"AN1\",\"inverted\": true,\"signed\": true},\"b\""
  ": {\"channel\": \"AN4\",\"inverted\": true,\"signed\": true},\"dcLink\": {\"chan"
  "nel\": \"AN0\",\"inverted\": false,\"signed\": true}},\"voltage\": {\"dcLink\": "
  "{\"channel\": \"AN12\",\"signed\": true},\"a\": {\"channel\": \"AN11\",\"signed"
  "\": false},\"b\": {\"channel\": \"AN10\",\"signed\": false},\"c\": {\"channel\":"
  " \"AN2\",\"signed\": false}},\"other\": {\"potentiometer\": {\"channel\": \"AN15"
  "\",\"signed\": true}},\"samplingTime\": {\"default\": 3e-07,\"minimum\": 3e-07,"
  "\"maximum\": 3e-07}},\"pwm\": {\"polarity\": {\"upper\": \"active-high\",\"lower"
  "\": \"active-high\"},\"generators\": {\"a\": 1,\"b\": 3,\"c\": 4},\"fault\": {\""
  "polarity\": \"active-high\",\"source\": \"CMP1\"}},\"opamp\": {\"enabled\": [1,2"
  ",3]},\"comparator\": {\"source\": \"CMP1A\",\"inverted\": false,\"threshold\": 0"
  ".95},\"gpio\": {\"MCAF_LED2\": {\"pin\": \"RB1\",\"direction\": \"output\",\"pol"
  "arity\": \"active-high\"},\"MCAF_BUTTON1\": {\"pin\": \"RC9\",\"direction\": \"i"
  "nput\",\"polarity\": \"active-high\"},\"MCAF_BUTTON2\": {\"pin\": \"RD12\",\"dir"
  "ection\": \"input\",\"polarity\": \"active-high\"}},\"uart\": {\"pins\": {\"RX\""
  ": \"RC7\",\"TX\": \"RD10\"}},\"debugger\": {\"channel\": 3}}},\"idc\": {\"units"
  "\": \"A\"},\"sampling_time\": {\"current\": 5e-05,\"velocity\": 0.001},\"process"
  "or\": {\"clock_frequency\": 100000000.0,\"device\": \"dsPIC33CDVC256MP506\"}},\""
  "config\": {\"ui\": {\"content\": {\"current_measure-method\": \"dual_channel\","
  "\"current_measure-single_channel-minimumTime\": 2.0,\"current_measure-single_cha"
  "nnel-sampleDelay\": 0.0,\"current_measure-opamp-full_input_range\": true,\"curre"
  "nt_measure-offset_cal-range\": 0.0625,\"estimator-type\": \"atpll\",\"estimator-"
  "active-pll\": false,\"estimator-active-smo\": false,\"estimator-active-qei\": fa"
  "lse,\"estimator-active-atpll\": true,\"estimator-active-zsmt\": false,\"estimato"
  "r-active-ideal\": false,\"operation-min_velocity_ratio\": 0.12,\"operation-start"
  "up_velocity_ratio\": 0.13,\"operation-max_velocity_ratio\": 1.25,\"operation-ful"
  "lscale_base_ratio\": 1.5,\"operation-outer_loop_type\": \"velocity\",\"operation"
  "-saliency-threshold\": 1.25,\"operation-slewrate-accel\": 0.5,\"operation-slewra"
  "te-decel\": 1.0,\"operation-dyn_current_type\": \"none\",\"operation-stopping-ty"
  "pe\": \"minimal_impact\",\"operation-stopping-closed_loop_parameters-speed\": 0."
  "05,\"operation-stopping-closed_loop_parameters-time\": 0.5,\"operation-stopping-"
  "coastdown-end_velocity\": 0.05,\"operation-stopping-coastdown-time\": 1.2,\"faul"
  "t_inject-get_tf-div0\": false,\"fault_inject-get_tf-missing_data\": false,\"faul"
  "t_inject-get_tf-raise_value_error\": false,\"fault_inject-get_tf-raise_custom_er"
  "ror\": false,\"fault_inject-tf-tf_null\": false,\"fault_inject-tf-tf_jy\": false"
  ",\"fault_inject-tf-tf_jyex\": false,\"fault_inject-tf-div0\": false,\"fault_inje"
  "ct-tf-tau\": 0.0,\"flux_control-method\": \"none\",\"flux_control-eqn_based-ilim"
  "it-region_type\": \"quadratic\",\"flux_control-eqn_based-ilimit-id_limit\": 0.7,"
  "\"flux_control-eqn_based-ilimit-iq_limit\": 0.95,\"flux_control-eqn_based-fluxwe"
  "ak_enable\": false,\"flux_control-eqn_based-fw-vdq_limit\": 0.95,\"flux_control-"
  "eqn_based-mtpa_enable\": false,\"deadtimecomp-method\": \"none\",\"deadtimecomp-"
  "perphase-current_sign_band\": 0.02,\"deadtimecomp-perphase-forward_gain\": 0.0,"
  "\"deadtimecomp-perphase-feedback_gain\": 0.0,\"fault_detect-margin_uv\": 4.0,\"f"
  "ault_detect-margin_ov\": 2.0,\"fault_detect-stall_detect_enable\": false,\"start"
  "up-Istartup\": 0.38,\"startup-t_rampup\": 25.0,\"startup-t_align\": 0.0,\"startu"
  "p-min_total_accel_time\": 250.0,\"startup-torque_scale_accel\": 0.15,\"startup-t"
  "orque_scale_slow_accel\": 0.2,\"startup-t_hold\": 0.0,\"startup-omega0\": 0.2,\""
  "startup-theta_converge_rate\": 1.0,\"startup-method\": \"weathervane\",\"startup"
  "-damping-Imax\": 0.133,\"startup-damping-gainmax\": 40.0,\"startup-damping-omega"
  "_min\": 0.4,\"overmodulation-vd_limit\": 1.0,\"overmodulation-vq_limit\": 1.15,"
  "\"overmodulation-include_duty_clipping\": true,\"atpll-tau1\": 0.075,\"atpll-tau"
  "2\": 2.19,\"atpll-kp\": 1.9,\"atpll-ki\": 30.0,\"pll-tau\": 2.19,\"pll-omega1\":"
  " 116.5,\"pll-velocity_filter_threshold\": 1.0,\"smo-velocity_loop_cutoff\": 0.3,"
  "\"encoder-lines\": 250.0,\"encoder-index_present\": false,\"encoder-tracking_loo"
  "p-tau\": 1.5,\"encoder-qei_sync-method\": \"align\",\"encoder-qei_sync-align-t_a"
  "lign\": 0.5,\"encoder-qei_sync-align-angle_shift\": 30.0,\"encoder-qei_sync-alig"
  "n-angle_init\": -30.0,\"encoder-qei_sync-align_sweep-sweep_rate_pow\": 1.0,\"enc"
  "oder-qei_sync-align_sweep-setup_angle\": 45.0,\"encoder-qei_sync-pullout-pullout"
  "_slip\": 0.117,\"zsmt-excitation-kV\": 0.12,\"zsmt-excitation-kI\": 0.1,\"zsmt-p"
  "ll-zeta\": 1.5,\"zsmt-pll-tau\": 10.0,\"zsmt-pll-tau_lpf\": 0.0,\"zsmt-pll-execu"
  "tion_divider\": 2.0,\"zsmt-startup-align_delay\": 1.0,\"zsmt-startup-pll_lock_ti"
  "me\": 1.0,\"zsmt-startup-speed_limit\": 0.015,\"zsmt-startup-current_limit\": 0."
  "3,\"zsmt-startup-probe_current\": 0.3,\"zsmt-startup-probe_duration\": 10.0,\"zs"
  "mt-startup-probe_slew_time\": 1.5,\"zsmt-startup-probe_blanking_time\": 4.0,\"zs"
  "mt-hybrid-type\": \"minotaur\",\"zsmt-minotaur-voltage_limit-vd\": 0.45,\"zsmt-m"
  "inotaur-voltage_limit-vq\": 0.78,\"zsmt-minotaur-converge-angle\": 10.0,\"zsmt-m"
  "inotaur-converge-duration\": 2.0,\"zsmt-minotaur-velocity_threshold-slow\": 0.15"
  ",\"zsmt-minotaur-velocity_threshold-transition\": 0.2,\"zsmt-minotaur-velocity_t"
  "hreshold-fast\": 0.25,\"zsmt-angle_correction-current_gain\": 0.0,\"dyn_current1"
  "-peak_factor\": 1.0,\"dyn_current1-horizon_factor\": 1.05,\"dyn_current1-tau\": "
  "5.0,\"dyn_current1-nsamples\": 128.0,\"voltage_outerloop-tau_lpf\": 2.0,\"voltag"
  "e_outerloop-Kp\": 0.1,\"voltage_outerloop-tau\": 100.0,\"mcapi-isSquaredTau\": 1"
  ".0,\"mcapi-iqTau\": 1.0,\"mcapi-adcIsrUserFunctions_enable\": false,\"board_serv"
  "ice-uiServiceTiming\": 1.0,\"board_service-uiButtonDebounceTime\": 7.0,\"board_s"
  "ervice-uiButtonLongPressTime\": 2.5,\"test_harness-perturbation_asymmetric\": fa"
  "lse,\"test_harness-codegen-test_harness\": true,\"test_harness-codegen-test_prof"
  "iling\": false,\"adc-vtempbridge\": false,\"adc-temp_bridge_params-threshold\": "
  "50.0,\"adc-temp_bridge_params-tau_lpf\": 10.0,\"adc-temp_bridge_params-slewrate"
  "\": 4.0,\"adc-vabsref\": false,\"adc-vphasea\": false,\"adc-vphaseb\": false,\"a"
  "dc-vphasec\": false,\"diagnostics-method\": \"x2cscope\"},\"version\": {\"schema"
  "\": 6.0,\"motorBench\": \"2.55.0-dev.10\",\"MCAF\": \"R9\"},\"status\": {\"valid"
  "\": true}}}}";